-- ============================================
-- 큐피 Kpop 리스트 INSERT
-- songbook Supabase (dpditjxvhmfxkxbtgaak)
-- ============================================

INSERT INTO songs (genre, artist, title, level, memo, is_signature) VALUES
('kpop', '아이유', '하루끝', 2, '', false),
('kpop', '달의하루', '염라', 3, '', false),
('kpop', '음율', '파도혁명', 3, '', false),
('kpop', '아이리 칸나', '최종화', 2, '', false),
('kpop', 'Fifty Fifty', 'Cupid (Twin Ver.)', 4, '', false),
('kpop', 'Warak', '났다는것은다시시작된다는것을 (산나비OST)', 4, '', false),
('kpop', 'FIFTY FIFTY', 'SOS', 3, '', false),
('kpop', 'Miiro', '괴물이피는숲', 3, '', false),
('kpop', '에스파', 'Welcome To MY World', 3, '', false),
('kpop', 'QWER', '내이름맑음', 4, '', false),
('kpop', '프로미스나인', 'Supersonic', 4, '', false),
('kpop', '프로미스나인', 'DM', 4, '', false),
('kpop', '백야', '첫사랑', 5, '', false),
('kpop', 'AOA', '짧은치마', 3, '', false),
('kpop', '걸스데이', 'Something', 3, '', false),
('kpop', '트와이스', 'Ooh-Ahh하게', 3, '', false),
('kpop', '소녀시대', 'Run Devil Run', 3, '', false),
('kpop', '씨스타', 'Give It To Me', 3, '', false),
('kpop', '원더걸스', 'Tell Me', 4, '', false),
('kpop', '카라', '맘마미아', 3, '', false),
('kpop', 'AOA', '사뿐사뿐', 3, '', false),
('kpop', 'NewJeans', 'How Sweet', 4, '', false),
('kpop', 'NewJeans', 'NewJeans', 4, '', false),
('kpop', 'NewJeans', 'Get Up', 5, '', false),
('kpop', 'NewJeans', 'Supernatural', 4, '', false),
('kpop', 'NewJeans', 'Right Now', 5, '', false),
('kpop', 'NewJeans', 'Ditto', 5, '', false),
('kpop', 'NewJeans', 'OMG', 4, '', false),
('kpop', 'NewJeans', 'ETA', 5, '', false),
('kpop', 'NewJeans', 'Hype boy', 3, '', false),
('kpop', 'NewJeans', 'Cookie', 4, '', false),
('kpop', 'NewJeans', 'ASAP', 5, '', false),
('kpop', 'NewJeans', 'Attention', 3, '', false),
('kpop', 'NewJeans', 'Super Shy', 4, '', false),
('kpop', 'NewJeans', 'Cool With You', 4, '', false),
('kpop', 'F(X)', '첫사랑니', 4, '', false),
('kpop', '체리필터', '오리날다', 3, '', false),
('kpop', '쥬얼리', '니가참좋아', 3, '', false),
('kpop', '콜드', '와르르', 3, '', false),
('kpop', '딘', 'Instagram', 2, '연습', false),
('kpop', '혁오', '위잉위잉 (여자키)', 4, '', false),
('kpop', '이선희', '여우비 (내여자친구는구미호OST)', 4, '', false),
('kpop', '에이핑크', 'Luv', 3, '', false),
('kpop', '레드벨벳', '러시안룰렛', 4, '', false),
('kpop', '에이핑크', 'Mr.Chu', 4, '', false),
('kpop', '티아라', 'Day By Day', 3, '', false),
('kpop', '소녀시대', 'Gee', 3, '', false),
('kpop', '소녀시대', '다시만난세계', 3, '', false),
('kpop', '김건모', '잘못된만남', 4, '', false),
('kpop', '자자', '버스안에서', 4, '', false),
('kpop', '거북이', '빙고', 4, '', false),
('kpop', '거북이', '비행기', 4, '', false),
('kpop', '이선희', '인연', 4, '', false),
('kpop', '안예은', '홍연', 4, '', false),
('kpop', '최예나', 'SMILEY', 4, '', false),
('kpop', '소녀시대', 'Mr. Mr.', 3, '', false),
('kpop', '소녀시대', 'Lion Heart', 4, '', false),
('kpop', '루시', '아니근데진짜', 4, '', false),
('kpop', 'ILLIT', 'Magnetic', 5, '', false),
('kpop', '르세라핌', 'Sour Grapes', 5, '', false),
('kpop', 'LUCY', '개화 (Flowering) (여자키)', 3, '', false),
('kpop', 'QWER', '수수께끼다이어리', 3, '', false),
('kpop', '이무진', '에피소드 (여자키)', 4, '', false),
('kpop', '넬', '기억을 걷는 시간 (태연 ver)', 4, '', false),
('kpop', '10cm', '스토커 (여자키)', 5, '', false),
('kpop', '여자아이들', '나는아픈건딱질색이니까', 5, '', false),
('kpop', '백예린', '우주를 건너', 4, '', false),
('kpop', '아이유', '밤편지', 3, '', false),
('kpop', '잔나비', '주저하는 연인들을 위해 (여자키)', 5, '', false),
('kpop', '크러쉬', '가끔 (여자키)', 4, '', false),
('kpop', '백예린', '그건아마우리의잘못은아닐거야', 4, '', false),
('kpop', '시드사운드', '여우별', 5, '', false),
('kpop', '서리', '긴밤', 4, '', false),
('kpop', '태연', 'To. X', 4, '', false),
('kpop', '경서', '나의 X에게', 4, '', false),
('kpop', '아이유', '그사람', 5, '', false),
('kpop', '10cm', '사랑은 은하수 다방에서', 5, '', false),
('kpop', '백예린', '우주를건너', 4, '', false),
('kpop', '태연', 'What Do I Call You', 5, '', false),
('kpop', '아이유', '레옹', 4, '', false),
('kpop', '아이유', '스물셋', 5, '', false),
('kpop', '볼빨간사춘기', '여행', 5, '', false),
('kpop', '악동뮤지션', '후라이의꿈', 3, '고음 x', false),
('kpop', '르세라핌', 'Perfect Night', 3, '', false),
('kpop', 'QWER', 'Discord', 4, '', false),
('kpop', '피프티피프티', 'CUPID (Twin Ver.)', 4, '', false),
('kpop', '아이유', '드라마', 4, '', false),
('kpop', '부석순', '파이팅해야지', 3, '랩 절음 ..', false),
('kpop', '러블리즈', 'Cameo', 4, '', false),
('kpop', '트와이스', '거북이', 3, '', false),
('kpop', '트와이스', 'Feel Special', 4, '', false),
('kpop', '에스파', 'Thirsty', 4, '', false),
('kpop', '에스파', 'Hold On Tight', 3, '', false),
('kpop', '아야츠노 유니', '내꺼 하는 법', 5, '', false),
('kpop', '이세계아이돌', 'LOCKDOWN', 2, '', false),
('kpop', '음율', '시시한 청춘에 남기는 노래', 4, '', false),
('kpop', '안예은', '창귀', 3, '', false),
('kpop', '비비', 'PADO', 4, '', false),
('kpop', '비비', '사장님 도박은 재미로 하셔야 합니다', 3, '', false),
('kpop', '비비', '밤양갱', 5, '', false),
('kpop', '티아라', 'Sexy Love', 3, '', false),
('kpop', '티아라', '왜이러니', 3, '', false),
('kpop', '티아라', 'Roly-Poly', 3, '', false),
('kpop', '티아라', '넘버나인', 3, '', false),
('kpop', '티아라', 'Sugar Free', 3, '', false),
('kpop', '씨스타', '나 혼자', 3, '', false),
('kpop', '청하', 'Everything Goes On (청하ver.)', 3, '', false),
('kpop', '볼빨간사춘기', '나만안되는연애', 3, '', false),
('kpop', '볼빨간사춘기', 'Blue', 4, '', false),
('kpop', '볼빨간사춘기', '처음부터너와나', 3, '', false),
('kpop', '심규선', '달과 6펜스', 4, '', false),
('kpop', '볼빨간사춘기', '나의 사춘기에게', 4, '', false),
('kpop', '아이유', '나의옛날이야기', 4, '', false),
('kpop', '경서', '밤하늘의별을', 3, '', false),
('kpop', '태연', '11시11 (11:11)', 5, '', false),
('kpop', '아이유', '비밀의화원', 4, '', false),
('kpop', '볼빨간사춘기', '워커홀릭', 4, '', false),
('kpop', '선우정아', '고양이', 4, '', false),
('kpop', '아이유', 'Blueming', 3, '', false),
('kpop', '잔나비', '사랑하긴했었나요스쳐가는인연이었나요', 5, '', false),
('kpop', '나래', '호랑수월가', 4, '', false),
('kpop', '시드사운드', '조각나비', 3, '까먹음', false),
('kpop', '오마이걸', 'Classified', 3, '', false),
('kpop', '에스파', '도깨비불(Illusion)', 3, '', false),
('kpop', '에스파', 'Whiplash', 3, '', false),
('kpop', '태연', '사계', 4, '', false),
('kpop', '볼빨간사춘기', '좋다고말해', 3, '', false),
('kpop', '10cm', '봄이좋냐??', 5, '', false),
('kpop', '에스파', 'Spicy', 3, '', false),
('kpop', '아이유', '이지금', 4, '', false),
('kpop', '최예나', '네모네모', 4, '', false),
('kpop', '태연', 'Melt Away', 4, '', false),
('kpop', '태연', 'Hot Mess', 4, '', false),
('kpop', '헤비', '늘(EVER)', 3, '', false),
('kpop', 'TAK', '도깨비꽃', 5, '', false),
('kpop', '헤비', '지금부터', 3, '', false),
('kpop', 'TAK', 'Lucky Doki', 3, '', false),
('kpop', '러블리즈', '미묘미묘해', 4, '', false),
('kpop', '아이브', 'Accendio', 3, '', false),
('kpop', '아이브', 'Off The Record', 3, '', false),
('kpop', '리센느', 'LOVE ATTACK', 4, '', false),
('kpop', '이세계아이돌', 'Stargazers', 3, '', false),
('kpop', '이세계아이돌', 'ELEVATE', 3, '', false),
('kpop', '이세계아이돌', 'KIDDING', 4, '', false),
('kpop', '허니즈', '3', 5, '', false),
('kpop', '이세계아이돌', '겨울봄', 3, '', false),
('kpop', '태연', 'Letter To Myself', 4, '', false),
('kpop', '에스파', 'Hot Mess', 3, '', false),
('kpop', '아이유', '잼잼', 4, '', false),
('kpop', '가인', 'Carnival', 5, '', false),
('kpop', '유니', 'SUPADOPA', 5, '', false),
('kpop', '윤하', '오르트구름', 3, '', false),
('kpop', '커피소년', '행복의주문', 4, '', false),
('kpop', '악동뮤지션', '어떻게 이별까지 사랑하겠어, 널 사랑하는 거지', 2, '', false),
('kpop', '정국', 'Still With You', 3, '', false),
('kpop', '아이유', '이런 엔딩', 4, '', false),
('kpop', '심규선', '월령月齡', 3, '', false),
('kpop', '볼빨간 사춘기', '썸 탈 꺼야', 4, '', false),
('kpop', '아이유', 'strawberry moon', 4, '', false),
('kpop', '악동뮤지션', '낙하', 3, '', false),
('kpop', '아일릿', 'Lucky Girl Syndrome', 4, '', false),
('kpop', '아일릿', '빌려온고양이', 3, '', false),
('kpop', '브레이브 걸스', '롤린', 3, '', false),
('kpop', '미쓰에이', 'Bad Girl Good Girl', 3, '', false),
('kpop', '이진아', 'Target for love (블루아카이브)', 5, '', false),
('kpop', '아이유', '애타는 마음', 4, '', false),
('kpop', '다즈비', '시간을넘어와줘', 3, '', false),
('kpop', '21학번', '스티커 사진', 4, '', false),
('kpop', '아이오아이', '소나기', 3, '', false),
('kpop', '김세정', '꽃길', 3, '마지막 고음 x', false),
('kpop', '아이유', '이름에게', 4, '', false),
('kpop', '주니엘', '나쁜사람', 3, '', false),
('kpop', '주니엘', 'illa illa(일라일라)', 4, '', false),
('kpop', '백아연', '이럴거면그러지말지', 5, '', false),
('kpop', '이츠', '청록', 4, '', false),
('kpop', '디핵', 'OHAYO MY NIGHT (여자키)', 4, '', false),
('kpop', '윤하', 'Black hole', 3, '', false),
('kpop', '한로로', '입춘', 4, '', false),
('kpop', '윤마치', '초록', 4, '', false),
('kpop', '아이유', 'Love poem', 4, '', false),
('kpop', '이수현', '연의편지', 3, '연습중', false),
('kpop', '신지훈', '추억은한편의산문집되어', 3, '', false),
('kpop', 'QWER', 'CEREMONY', 4, '', false),
('kpop', '투모로우바이투게더', '하루에하루만더', 3, '', false),
('kpop', '치즈', '좋아해(Bye)', 3, '', false),
('kpop', '치즈', '어떻게생각해', 4, '', false),
('kpop', '음율', '반비례', 4, '', false),
('kpop', '넬', '기억을걷는시간 (여자키)', 3, '', false),
('kpop', '한로로', '0+0', 4, '', false),
('kpop', 'KiiiKiii(키키)', '404(New Era)', 4, '', false),
('kpop', '하츠투하츠', 'RUDE!', 5, '', false),
('kpop', '한로로', '사랑하게될거야', 4, '', false),
('kpop', '백예린', '야간비행', 4, '', false),
('kpop', '하츠투하츠', 'STYLE', 3, '', false),
('kpop', '하츠투하츠', 'The Chase', 3, '', false),
('kpop', '마로니에', '칵테일사랑', 4, '', false),
('kpop', '레드벨벳', '빨간 맛', 3, '', false),
('kpop', '조이', '안녕(Hello)', 3, '', false),
('kpop', '숀', '터미널 (여자키)', 5, '', false),
('kpop', '유다연', 'DokiDoki♥', 4, '', false),
('kpop', '히미츠', '신장개업', 3, '', false),
('kpop', '숀', '밤산책 (여자키)', 5, '', false),
('kpop', '데이먼스이어', 'yours (여자키)', 4, '', false),
('kpop', '지코', '너는나나는너 (여자키)', 3, '', false),
('kpop', 'Chan, 기원', '끊었어?', 3, '', false),
('kpop', '음율', '시시한청춘에남기는노래', 4, '', false),
('kpop', '백예린', 'Antifreeze', 5, '', false),
('kpop', '우예린', '붉은장미', 5, '', false),
('kpop', '투모로우바이투게더', 'Over The Moon (여자키)', 4, '', false),
('kpop', '스텔라장', '우르릉쾅쾅쾅', 3, '', false),
('kpop', 'G-DRAGON', '그XX', 4, '', false),
('kpop', '하츠투하츠', 'FOCUS', 4, '', false),
('kpop', '지코', '걘 아니야 (여자키)', 3, '', false),
('kpop', '최유리', '숲', 4, '', false),
('kpop', '아이린', 'Like A Flower', 3, '', false),
('kpop', '우효', '민들레', 4, '', false),
('kpop', '라붐', '상상더하기', 3, '', false),
('kpop', '레드벨벳', 'Rookie', 4, '', false);
